JOB_TYPE=$jobtype
GRID_JOBID=$gridjobid
LRMS_TYPE=$lrmstype
LRMS_JOBID=$lrmsjobid
LRMS_EVENTTIME=$lrmseventtime
LRMS_SUBMTIME=$lrmssubmtime
USER_DN=$userdn
USER_FQAN=$userfqan
CE_ID=$ceid
timeZone=+0200
GlueHostApplicationSoftwareRunTimeEnvironment: SI00MeanPerCPU=1495
GlueHostBenchmarkSI00=1495
GlueHostBenchmarkSF00=1268
GlueHostApplicationSoftwareRunTimeEnvironment: SF00MeanPerCPU=1268
ACCTLOG:05/20/2008 18:25:17;E;$lrmsjobid;user=$unixuser group=$unixgroup jobname=STDIN queue=$queue ctime=$ctime qtime=$qtime etime=$etime start=$start exec_host=t2-wnU-16.to.infn.it/1 Resource_List.cput=48:00:00 Resource_List.neednodes=1 Resource_List.nodect=1 Resource_List.nodes=1 Resource_List.walltime=72:00:00 session=1876 end=1211300717 Exit_status=0 resources_used.cput=$cputime resources_used.mem=$mem resources_used.vmem=$vmem resources_used.walltime=$walltime
